name: qtchildid
version: '1.0-alpha'
summary: QT4-based Child ID System
description: |
  QT4-based Child ID system used to conduct Child ID events. It allows
  you to register a child, take fingerprints and print IDs containing
  relevant data in case of a child abduction scenario. The data is
  deleted after each entry and not stored remotely at any point.
type: app
grade: devel
confinement: strict
apps:
  qtchildid:
    command: qt4-launch QtChildID
    desktop: qtchildid.desktop
    plugs:
      - hardware-observe
      - network-observe
      - camera
      - x11
      - raw-usb
parts:
  app:
    plugin: qmake
    source: .
    qt-version: qt4
    project-files:
      - QtChildID.pro
    stage-packages:
      - libqtgui4
      - libfprint0
      - libpoppler-qt4-4
      - libopencv-highgui2.4v5
      - libopencv-core2.4v5
    build-packages:
      - qt4-default
      - libopencv-dev
      - libpoppler-qt4-dev
      - libfprint-dev
    install: |
      mkdir $SNAPCRAFT_PART_INSTALL/bin
      cp QtChildID $SNAPCRAFT_PART_INSTALL/bin/
    after: [qt4conf] 
